name: manage-azure-policy-dfe9ec1a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'init/initiatives/Basic-Compliance-Posture_28dd2a5f2dbf4a59aa198376/**'
#      - .github/workflows/manage-azure-policy-dfe9ec1a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_dfe9ec1a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          init/initiatives/Basic-Compliance-Posture_28dd2a5f2dbf4a59aa198376/**
